### ISSUE TITLE
C2: improve issue message?

### ISSUE THREAD

**Issue by hohwille** [devonfw/sonar-devon-plugin#11]
From #5:

> Rule C2
> This message seems to tell me that general dependencies are allowed, which means… that I can use any dependency? But then why do I have an issue:
> ![c2-eb24f725671807a1b5b1a689290f3d2d557d03db](https://user-images.githubusercontent.com/1923119/50073140-f1553380-01d7-11e9-97fa-8b20bc0694b7.jpeg)

**Comment by hohwille** [comment]
This is more of a missunderstanding: Here `general` is the name of a predefined technical and cross-cutting component (see https://github.com/devonfw/devon4j/wiki/coding-conventions#packages). There are two implicit components that do not need to be defined explicitly in `architecture.json`:
* `general` (may not depend on any other component but all other components may depend on it, used for cross-cutting code)
* `application` (may depend on any other component but no other component may depend on it, used for assembly and orchestration of the application such as spring config classes).

I think about improving the issue message but consider this as nice to have and low prio.

**Comment by ganncamp** [comment]
@hohwille this sounds like fodder not for the issue message (remember the length limit) but the rule description.

**Comment by hohwille** [comment]
> @hohwille this sounds like fodder not for the issue message (remember the length limit) but the rule description.

Thanks for the feedback. Will be addressed with #33 

This issue itself is done with PR #30
