### ISSUE TITLE
Travis CI build fails and exits during JDK installation

### ISSUE THREAD

**Issue by lmarniazman** [devonfw/sonar-devon-plugin#21]
When opening a new pull request, the Travis CI check can't run through because of a failing JDK installation. A quick google search showed that this has been an issue since the end of last year with Travis and the oraclejdk8. 
In PR #19 the JDK installation worked fine. As far as I can tell, this is because there the property 'dist' was set to 'trusty', whereas in my PR #20 it was set to 'xenial'. This is weird, because both PRs are working with the exact same .travis.yml file.

_Log of failed build - Overview_
![log_of_failed_build-overview](https://user-images.githubusercontent.com/49903872/59765006-511ebb00-929d-11e9-8200-17751def7e18.PNG)

_Log of failed build - Build system information_
![log_of_failed_build-build_system_information](https://user-images.githubusercontent.com/49903872/59765098-87f4d100-929d-11e9-8e28-1a3eb24c78fa.PNG)

**Comment by hohwille** [comment]
We had this issue with all our github repos. Thanks for PR #22. Merged.
